apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volantmq
  namespace: monitoring
  labels:
    k8s-app: volantmq
spec:
  selector:
    matchLabels:
      k8s-app: volantmq
  endpoints:
  - port: monitoring
    path: /metrics
    interval: 5s
  namespaceSelector:
    matchNames:
      - volantmq
